Matrices (Rank 2 tensors):

In [2]:
import numpy as np 

In [3]:
#matrices are written in capital letters
X = np. array([[25, 2], [5, 6], [6, 10]])

In [4]:
#shape
print(X.shape)

#size
print(X.size)

(3, 2)
6


Slicing matrices

In [6]:
#matrices shapes are in the form of (rows, columns)
#we can have a single row specifying the row index and the : operator
row_0 = X[0, :]
row_1 = X[1, :]
row_2 = X[2, :]

#we can have a single column specifying the column index and the : operator
col_0 = X[:, 0]
col_1 = X[:, 1]

print(row_0)
print(row_1)
print(row_2)

print(col_0)
print(col_1)

[25  2]
[5 6]
[ 6 10]
[25  5  6]
[ 2  6 10]


Tensor Transposition

In [9]:
#transposition is to flip the axios over the main diagonal
#we can also say that its flipping the columns and the rows
print(X)
print(X.T)

[[25  2]
 [ 5  6]
 [ 6 10]]
[[25  5  6]
 [ 2  6 10]]


Reduction - Minimum - Maximum - Mean

In [17]:
#Tensor reduction
print(np.sum(X))

#Tensor column reduction
print(np.sum(X, axis=0))

#Tensor row reduction
print(np.sum(X, axis=1))

#Tensor Min
print(np.min(X))

#Tensor Max
print(np.max(X))

#Tensor Mean
print(np.mean(X))

#Tensor column mean
print(np.mean(X, axis=0))
print(np.mean(X[:, 0]))

54
[36 18]
[27 11 16]
2
25
9.0
[12.  6.]
12.0


Dot product

In [27]:

#in order to perform dot product we need to matrices where the number of columns of X1 is
#equal to the number of rows of X2
#the dot product is not commutative

#X1.shape = (2,2)
X1 = np.array([[4, 5], [3, 2]])

#X2.shape = (2, 4)
X2 = np.array([[3, 4, 1, 3], [4, 5, 5, 4]])

print('X1 shape' + str(X1.shape))
print('X2 shape' + str(X2.shape))

print('(X1, X2) dot product' + str(np.dot(X1, X2)))
#print('(X2, X1) dot product' + str(np.dot(X2, X1)))

X1 shape(2, 2)
X2 shape(2, 4)
(X1, X2) dot product[[32 41 29 32]
 [17 22 13 17]]
