In [1]:
import numpy as np

In [27]:
I3  = np.array([[1,0,0],[0,1,0],[0,0,1]])
K = np.array([[2/3,1/3,2/3],[-2/3,2/3,1/3],[1/3,2/3,-2/3]])

col_0 = I3[:, 0]
col_1 = I3[:, 1]
col_2 = I3[:, 2]

#All the columns and rows should be orthogonal to each other
#so the dot product should be 0
print(np.dot(col_0, col_1))
print(np.dot(col_0, col_2))
print(np.dot(col_1, col_2))

#and they should have unit norm
print(np.linalg.norm(col_0))
print(np.linalg.norm(col_1))
print(np.linalg.norm(col_2))


0
0
0
1.0
1.0
1.0


In [38]:
def is_orthogonal(matrix):
    for i in range(len(matrix)):
        for j in range(i + 1, len(matrix)):
            if np.dot(matrix[:, i], matrix[:, j]) != 0 or np.dot(matrix[i, :], matrix[j, :]) != 0:
                return False
        if np.linalg.norm(matrix[:, i]) != 1 or np.linalg.norm(matrix[i, :]) != 1:
            return False
    return True

print(is_orthogonal(I3))
print(is_orthogonal(K))

#if we multiply the matrix and the transpose the result should be the identity matrix
I_result = np.dot(K.T, K)
I_result = np.array(I_result, dtype=np.float16)
print(I_result)

True
True
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
